// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'Item.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

Item _$ItemFromJson(Map<String, dynamic> json) {
  return Item(
      json['id'] as int,
      json['recordCreateTime'] as String,
      json['baseCode'] as String,
      json['itemNo'] as String,
      json['itemName'] as String,
      json['allSpelling'] as String,
      json['firstSpelling'] as String,
      json['regId'] as int,
      json['depId'] as int,
      json['jgzfDepId'] as int,
      json['isWebShow'] as String,
      json['webDoDepth'] as String,
      json['isSlSMS'] as String,
      json['isBjSMS'] as String,
      json['isOrder'] as String,
      json['itemCategory'] as String,
      json['itemType'] as String,
      json['themeCitizen'] as String,
      json['themeCompany'] as String,
      json['serviceObject'] as String,
      json['doAddress'] as String,
      json['consultPhone'] as String,
      json['complaintPhone'] as String,
      json['exeLevel'] as String,
      json['setBasis'] as String,
      json['applycon'] as String,
      json['authorityDivision'] as String,
      json['exeContent'] as String,
      json['doPro'] as String,
      json['question'] as String,
      json['orgNature'] as String,
      json['unionOrg'] as String,
      json['agencyService'] as String,
      json['numLimit'] as String,
      json['ifcharge'] as String,
      json['isNoChargeDo'] as String,
      json['chargelist'] as String,
      json['version'] as String,
      json['chargeBasis'] as String,
      json['powerType'] as String,
      json['powerState'] as String,
      json['enabled'] as String,
      json['isVerify'] as String,
      json['verifyState'] as String,
      json['chargeType'] as String,
      json['callType'] as String,
      json['jumpUrl'] as String,
      json['acceptLimit'] as String,
      json['isPush'] as String,
      json['pushContent'] as String,
      json['isPrint'] as String,
      json['isHall'] as String,
      json['callPrior'] as int,
      json['legalLimit'] as int,
      json['consentLimit'] as int,
      json['resultName'] as String,
      json['resultSample'] as String,
      json['opeScope'] as String,
      json['dealType'] as String,
      json['isPay'] as String,
      json['isExpress'] as String,
      json['runSystem'] as String,
      json['processTime'] as String,
      json['processDescription'] as String,
      json['effectTime'] as String,
      json['custFormIds'] as String,
      json['itemFrom'] as String,
      json['updateDate'] as String,
      json['limitNum'] as int,
      json['personNum'] as int,
      json['telLimitNum'] as int,
      json['webapplyLimit'] as int,
      json['runNum'] as int,
      json['isAutoBespeak'] as String,
      json['quhaoEndTime'] as String,
      json['quhaoTip'] as String,
      json['doTime'] as int,
      json['isQuhaojiShow'] as String,
      json['quhaoOrder'] as int,
      json['isInputTel'] as String,
      json['lifeCycleCitizen'] as String,
      json['taskVersion'] as int,
      json['taskCode'] as String,
      json['taskHandleItem'] as String,
      json['isTaskHandleItem'] as String,
      json['isClaim'] as String,
      json['reconsiderOuname'] as String,
      json['reconsiderAddress'] as String,
      json['reconsiderContact'] as String,
      json['litigationOuname'] as String,
      json['litigationAddress'] as String,
      json['litigationContact'] as String,
      json['punishmentMethod'] as String,
      json['collectType'] as String,
      json['isPermitReduce'] as String,
      json['taskGuid'] as String,
      json['taskOrgName'] as String,
      json['taskDeptCode'] as String,
      json['integrity'] as String,
      json['forbidden'] as String,
      json['testTemp'] as String,
      json['lifeCycleCompany'] as String,
      json['callUserId'] as int,
      json['regName'] as String,
      json['depName'] as String,
      json['jgzfDepName'] as String,
      json['directoryListName'] as String,
      (json['listUpFiles'] as List)
          ?.map((e) =>
              e == null ? null : Upfiles.fromJson(e as Map<String, dynamic>))
          ?.toList(),
      (json['listWordUpFiles'] as List)
          ?.map((e) =>
              e == null ? null : Upfiles.fromJson(e as Map<String, dynamic>))
          ?.toList(),
      (json['listStuff'] as List)
          ?.map((e) =>
              e == null ? null : ItemStuff.fromJson(e as Map<String, dynamic>))
          ?.toList(),
      (json['listStuffCatalog'] as List)
          ?.map((e) => e == null
              ? null
              : StuffCatalog.fromJson(e as Map<String, dynamic>))
          ?.toList(),
      (json['listVersion'] as List)
          ?.map((e) =>
              e == null ? null : Item.fromJson(e as Map<String, dynamic>))
          ?.toList(),
      (json['listAccoptUser'] as List)
          ?.map((e) =>
              e == null ? null : UserInfo.fromJson(e as Map<String, dynamic>))
          ?.toList(),
      (json['listLicenceModel'] as List)
          ?.map((e) => e == null
              ? null
              : ItemLicenceModel.fromJson(e as Map<String, dynamic>))
          ?.toList(),
      json['doDepName'] as String,
      json['sessionUserId'] as int,
      json['warningDate'] as String,
      json['consentDate'] as String,
      json['legalDate'] as String,
      json['webApplyDate'] as String,
      json['warningLimit'] as int,
      (json['depIds'] as List)?.map((e) => e as int)?.toList(),
      json['nodeid'] as int,
      json['acceptType'] as String,
      json['businessId'] as int,
      json['isAllFlowComplete'] as String,
      json['allNum'] as String,
      json['wshNum'] as String,
      json['tgNum'] as String,
      json['wtgNum'] as String,
      json['acceptNum'] as String,
      json['tgl'] as String,
      json['sll'] as String,
      json['themes'] as String,
      json['callWindowId'] as int,
      json['callWindowStr'] as String,
      json['callAreaId'] as int,
      json['checked'] as String,
      json['acceptUsernames'] as String,
      json['sampleNum'] as int,
      json['callCatalogId'] as int,
      json['serviceObjectChoose'] as String,
      json['serviceObjectCh'] as String,
      json['waitNum'] as int,
      json['hmys'] as int,
      json['mys'] as int,
      json['jbmys'] as int,
      json['bmys'] as int,
      json['hbmys'] as int,
      json['cxdate'] as String,
      json['dayNum'] as int,
      json['hasNum'] as int,
      json['registerState'] as String,
      json['quhaoNum'] as int,
      json['isCollect'] as String,
      json['userCollectionId'] as int,
      json['isOverQuhaoTime'] as String,
      json['nextItemName'] as String,
      json['type'] as String,
      (json['listWindowUser'] as List)
          ?.map((e) =>
              e == null ? null : UserInfo.fromJson(e as Map<String, dynamic>))
          ?.toList(),
      (json['listLicenceCatalog'] as List)
          ?.map((e) => e == null
              ? null
              : ItemLicenceCatalog.fromJson(e as Map<String, dynamic>))
          ?.toList(),
      json['callAreaName'] as String,
      json['hasCallwindow'] as String,
      (json['listHyjgUser'] as List)
          ?.map((e) =>
              e == null ? null : UserInfo.fromJson(e as Map<String, dynamic>))
          ?.toList(),
      (json['listXzzfUser'] as List)
          ?.map((e) =>
              e == null ? null : UserInfo.fromJson(e as Map<String, dynamic>))
          ?.toList(),
      json['catalogName'] as String,
      json['serviceObjectType'] as String);
}

Map<String, dynamic> _$ItemToJson(Item instance) => <String, dynamic>{
      'id': instance.id,
      'recordCreateTime': instance.recordCreateTime,
      'baseCode': instance.baseCode,
      'itemNo': instance.itemNo,
      'itemName': instance.itemName,
      'allSpelling': instance.allSpelling,
      'firstSpelling': instance.firstSpelling,
      'regId': instance.regId,
      'depId': instance.depId,
      'jgzfDepId': instance.jgzfDepId,
      'isWebShow': instance.isWebShow,
      'webDoDepth': instance.webDoDepth,
      'isSlSMS': instance.isSlSMS,
      'isBjSMS': instance.isBjSMS,
      'isOrder': instance.isOrder,
      'itemCategory': instance.itemCategory,
      'itemType': instance.itemType,
      'themeCitizen': instance.themeCitizen,
      'themeCompany': instance.themeCompany,
      'serviceObject': instance.serviceObject,
      'doAddress': instance.doAddress,
      'consultPhone': instance.consultPhone,
      'complaintPhone': instance.complaintPhone,
      'exeLevel': instance.exeLevel,
      'setBasis': instance.setBasis,
      'applycon': instance.applycon,
      'authorityDivision': instance.authorityDivision,
      'exeContent': instance.exeContent,
      'doPro': instance.doPro,
      'question': instance.question,
      'orgNature': instance.orgNature,
      'unionOrg': instance.unionOrg,
      'agencyService': instance.agencyService,
      'numLimit': instance.numLimit,
      'ifcharge': instance.ifcharge,
      'isNoChargeDo': instance.isNoChargeDo,
      'chargelist': instance.chargelist,
      'version': instance.version,
      'chargeBasis': instance.chargeBasis,
      'powerType': instance.powerType,
      'powerState': instance.powerState,
      'enabled': instance.enabled,
      'isVerify': instance.isVerify,
      'verifyState': instance.verifyState,
      'chargeType': instance.chargeType,
      'callType': instance.callType,
      'jumpUrl': instance.jumpUrl,
      'acceptLimit': instance.acceptLimit,
      'isPush': instance.isPush,
      'pushContent': instance.pushContent,
      'isPrint': instance.isPrint,
      'isHall': instance.isHall,
      'callPrior': instance.callPrior,
      'legalLimit': instance.legalLimit,
      'consentLimit': instance.consentLimit,
      'resultName': instance.resultName,
      'resultSample': instance.resultSample,
      'opeScope': instance.opeScope,
      'dealType': instance.dealType,
      'isPay': instance.isPay,
      'isExpress': instance.isExpress,
      'runSystem': instance.runSystem,
      'processTime': instance.processTime,
      'processDescription': instance.processDescription,
      'effectTime': instance.effectTime,
      'custFormIds': instance.custFormIds,
      'itemFrom': instance.itemFrom,
      'updateDate': instance.updateDate,
      'limitNum': instance.limitNum,
      'personNum': instance.personNum,
      'telLimitNum': instance.telLimitNum,
      'webapplyLimit': instance.webapplyLimit,
      'runNum': instance.runNum,
      'isAutoBespeak': instance.isAutoBespeak,
      'quhaoEndTime': instance.quhaoEndTime,
      'quhaoTip': instance.quhaoTip,
      'doTime': instance.doTime,
      'isQuhaojiShow': instance.isQuhaojiShow,
      'quhaoOrder': instance.quhaoOrder,
      'isInputTel': instance.isInputTel,
      'lifeCycleCitizen': instance.lifeCycleCitizen,
      'taskVersion': instance.taskVersion,
      'taskCode': instance.taskCode,
      'taskHandleItem': instance.taskHandleItem,
      'isTaskHandleItem': instance.isTaskHandleItem,
      'isClaim': instance.isClaim,
      'reconsiderOuname': instance.reconsiderOuname,
      'reconsiderAddress': instance.reconsiderAddress,
      'reconsiderContact': instance.reconsiderContact,
      'litigationOuname': instance.litigationOuname,
      'litigationAddress': instance.litigationAddress,
      'litigationContact': instance.litigationContact,
      'punishmentMethod': instance.punishmentMethod,
      'collectType': instance.collectType,
      'isPermitReduce': instance.isPermitReduce,
      'taskGuid': instance.taskGuid,
      'taskOrgName': instance.taskOrgName,
      'taskDeptCode': instance.taskDeptCode,
      'integrity': instance.integrity,
      'forbidden': instance.forbidden,
      'testTemp': instance.testTemp,
      'lifeCycleCompany': instance.lifeCycleCompany,
      'callUserId': instance.callUserId,
      'regName': instance.regName,
      'depName': instance.depName,
      'jgzfDepName': instance.jgzfDepName,
      'directoryListName': instance.directoryListName,
      'listUpFiles': instance.listUpFiles,
      'listWordUpFiles': instance.listWordUpFiles,
      'listStuff': instance.listStuff,
      'listStuffCatalog': instance.listStuffCatalog,
      'listVersion': instance.listVersion,
      'listAccoptUser': instance.listAccoptUser,
      'listLicenceModel': instance.listLicenceModel,
      'doDepName': instance.doDepName,
      'sessionUserId': instance.sessionUserId,
      'warningDate': instance.warningDate,
      'consentDate': instance.consentDate,
      'legalDate': instance.legalDate,
      'webApplyDate': instance.webApplyDate,
      'warningLimit': instance.warningLimit,
      'depIds': instance.depIds,
      'nodeid': instance.nodeid,
      'acceptType': instance.acceptType,
      'businessId': instance.businessId,
      'isAllFlowComplete': instance.isAllFlowComplete,
      'allNum': instance.allNum,
      'wshNum': instance.wshNum,
      'tgNum': instance.tgNum,
      'wtgNum': instance.wtgNum,
      'acceptNum': instance.acceptNum,
      'tgl': instance.tgl,
      'sll': instance.sll,
      'themes': instance.themes,
      'callWindowId': instance.callWindowId,
      'callWindowStr': instance.callWindowStr,
      'callAreaId': instance.callAreaId,
      'checked': instance.checked,
      'acceptUsernames': instance.acceptUsernames,
      'sampleNum': instance.sampleNum,
      'callCatalogId': instance.callCatalogId,
      'serviceObjectChoose': instance.serviceObjectChoose,
      'serviceObjectCh': instance.serviceObjectCh,
      'waitNum': instance.waitNum,
      'hmys': instance.hmys,
      'mys': instance.mys,
      'jbmys': instance.jbmys,
      'bmys': instance.bmys,
      'hbmys': instance.hbmys,
      'cxdate': instance.cxdate,
      'dayNum': instance.dayNum,
      'hasNum': instance.hasNum,
      'registerState': instance.registerState,
      'quhaoNum': instance.quhaoNum,
      'isCollect': instance.isCollect,
      'userCollectionId': instance.userCollectionId,
      'isOverQuhaoTime': instance.isOverQuhaoTime,
      'nextItemName': instance.nextItemName,
      'type': instance.type,
      'listWindowUser': instance.listWindowUser,
      'listLicenceCatalog': instance.listLicenceCatalog,
      'callAreaName': instance.callAreaName,
      'hasCallwindow': instance.hasCallwindow,
      'listHyjgUser': instance.listHyjgUser,
      'listXzzfUser': instance.listXzzfUser,
      'catalogName': instance.catalogName,
      'serviceObjectType': instance.serviceObjectType
    };
