// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'Licence.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

Licence _$LicenceFromJson(Map<String, dynamic> json) {
  return Licence(
      json['id'] as int,
      json['recordCreateTime'] as String,
      json['licenceCatalogId'] as int,
      json['regId'] as int,
      json['depId'] as int,
      json['modelName'] as String,
      json['modelId'] as int,
      json['modelWidth'] as String,
      json['modelHeight'] as String,
      json['backImage'] as int,
      json['licenceNo'] as String,
      json['usefulDate'] as String,
      json['textJson'] as String,
      json['fieldJson'] as String,
      json['qrJson'] as String,
      json['imgJson'] as String,
      json['licenceLevel'] as String,
      json['holderType'] as String,
      json['holderCardNo'] as String,
      json['holderCompanyNo'] as String,
      json['state'] as String,
      json['version'] as String,
      json['hasCreate'] as String,
      json['waterContent'] as String,
      json['imageId'] as String,
      json['pdfId'] as String,
      json['hasSign'] as String,
      json['enabled'] as String,
      json['signatureJson'] as String,
      json['licenceStatus'] as String,
      json['checkType'] as String,
      json['ycInfoJson'] as String,
      json['issueDate'] as String,
      json['useStopDate'] as String,
      json['businessId'] as int,
      json['catalogHolderId'] as int,
      json['catalogName'] as String,
      json['uuid'] as String,
      json['fileName'] as String,
      json['filepath'] as String,
      json['useCount'] as int,
      json['depName'] as String,
      json['holderName'] as String,
      json['regName'] as String,
      json['unm'] as int,
      json['licenceState'] as String,
      json['yearCheck'] as String,
      json['pdfPath'] as String,
      json['pdfUuid'] as String,
      json['pdfFileName'] as String,
      json['imgUuid'] as String,
      json['imgFileName'] as String);
}

Map<String, dynamic> _$LicenceToJson(Licence instance) => <String, dynamic>{
      'id': instance.id,
      'recordCreateTime': instance.recordCreateTime,
      'licenceCatalogId': instance.licenceCatalogId,
      'regId': instance.regId,
      'depId': instance.depId,
      'modelName': instance.modelName,
      'modelId': instance.modelId,
      'modelWidth': instance.modelWidth,
      'modelHeight': instance.modelHeight,
      'backImage': instance.backImage,
      'licenceNo': instance.licenceNo,
      'usefulDate': instance.usefulDate,
      'textJson': instance.textJson,
      'fieldJson': instance.fieldJson,
      'qrJson': instance.qrJson,
      'imgJson': instance.imgJson,
      'licenceLevel': instance.licenceLevel,
      'holderType': instance.holderType,
      'holderCardNo': instance.holderCardNo,
      'holderCompanyNo': instance.holderCompanyNo,
      'state': instance.state,
      'version': instance.version,
      'hasCreate': instance.hasCreate,
      'waterContent': instance.waterContent,
      'imageId': instance.imageId,
      'pdfId': instance.pdfId,
      'hasSign': instance.hasSign,
      'enabled': instance.enabled,
      'signatureJson': instance.signatureJson,
      'licenceStatus': instance.licenceStatus,
      'checkType': instance.checkType,
      'ycInfoJson': instance.ycInfoJson,
      'issueDate': instance.issueDate,
      'useStopDate': instance.useStopDate,
      'businessId': instance.businessId,
      'catalogHolderId': instance.catalogHolderId,
      'catalogName': instance.catalogName,
      'uuid': instance.uuid,
      'fileName': instance.fileName,
      'filepath': instance.filepath,
      'useCount': instance.useCount,
      'depName': instance.depName,
      'holderName': instance.holderName,
      'regName': instance.regName,
      'unm': instance.unm,
      'licenceState': instance.licenceState,
      'yearCheck': instance.yearCheck,
      'pdfPath': instance.pdfPath,
      'pdfUuid': instance.pdfUuid,
      'pdfFileName': instance.pdfFileName,
      'imgUuid': instance.imgUuid,
      'imgFileName': instance.imgFileName
    };
