// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'Proposer.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

Proposer _$ProposerFromJson(Map<String, dynamic> json) {
  return Proposer(
      json['id'] as int,
      json['recordCreateTime'] as String,
      json['userName'] as String,
      json['userTel'] as String,
      json['userCardNo'] as String,
      json['userAddress'] as String,
      json['userSex'] as String,
      json['userPhone'] as String,
      json['userEmail'] as String,
      json['familyName'] as String,
      json['birthday'] as String,
      json['naturalState'] as String,
      json['companyName'] as String,
      json['companyType'] as String,
      json['companyTypeCode'] as String,
      json['companyLegalPersonName'] as String,
      json['companyLegalPersonCardNo'] as String,
      json['companyNo'] as String,
      json['orgCode'] as String,
      json['companyAddress'] as String,
      json['companyRegDate'] as String,
      json['businessScope'] as String,
      json['managementProject'] as String,
      json['companyRegisterMoney'] as String,
      json['companyRealMoney'] as String,
      json['companyTradeType'] as String,
      json['companyTradeSmall'] as String,
      json['companyStartDate'] as String,
      json['companyEndDate'] as String,
      json['companyCheckDate'] as String,
      json['companyRegOrg'] as String,
      json['companyEmail'] as String,
      json['companyPhone'] as String,
      json['companyState'] as String,
      json['linkUserName'] as String,
      json['linkTel'] as String,
      json['linkCardNo'] as String,
      json['linkAddress'] as String,
      json['linkSex'] as String,
      json['linkPhone'] as String,
      json['linkEmail'] as String,
      json['linkPostcode'] as String,
      json['userSexName'] as String,
      json['linkSexName'] as String,
      json['picCode'] as String);
}

Map<String, dynamic> _$ProposerToJson(Proposer instance) => <String, dynamic>{
      'id': instance.id,
      'recordCreateTime': instance.recordCreateTime,
      'userName': instance.userName,
      'userTel': instance.userTel,
      'userCardNo': instance.userCardNo,
      'userAddress': instance.userAddress,
      'userSex': instance.userSex,
      'userPhone': instance.userPhone,
      'userEmail': instance.userEmail,
      'familyName': instance.familyName,
      'birthday': instance.birthday,
      'naturalState': instance.naturalState,
      'companyName': instance.companyName,
      'companyType': instance.companyType,
      'companyTypeCode': instance.companyTypeCode,
      'companyLegalPersonName': instance.companyLegalPersonName,
      'companyLegalPersonCardNo': instance.companyLegalPersonCardNo,
      'companyNo': instance.companyNo,
      'orgCode': instance.orgCode,
      'companyAddress': instance.companyAddress,
      'companyRegDate': instance.companyRegDate,
      'businessScope': instance.businessScope,
      'managementProject': instance.managementProject,
      'companyRegisterMoney': instance.companyRegisterMoney,
      'companyRealMoney': instance.companyRealMoney,
      'companyTradeType': instance.companyTradeType,
      'companyTradeSmall': instance.companyTradeSmall,
      'companyStartDate': instance.companyStartDate,
      'companyEndDate': instance.companyEndDate,
      'companyCheckDate': instance.companyCheckDate,
      'companyRegOrg': instance.companyRegOrg,
      'companyEmail': instance.companyEmail,
      'companyPhone': instance.companyPhone,
      'companyState': instance.companyState,
      'linkUserName': instance.linkUserName,
      'linkTel': instance.linkTel,
      'linkCardNo': instance.linkCardNo,
      'linkAddress': instance.linkAddress,
      'linkSex': instance.linkSex,
      'linkPhone': instance.linkPhone,
      'linkEmail': instance.linkEmail,
      'linkPostcode': instance.linkPostcode,
      'userSexName': instance.userSexName,
      'linkSexName': instance.linkSexName,
      'picCode': instance.picCode
    };
